version: "3.9"
services:
  app:
    build: .
    container_name: ord-tutorial-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tutorial_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql-db
    restart: always

  mysql-db:
    image: mysql:8.1
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutorial_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

#  redis:
#    image: redis:7.2-alpine
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis-data:/data
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.4.1
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: confluentinc/cp-kafka:7.4.1
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#    ports:
#      - "9092:9092"  # port for internal communication
#      - "29092:29092" # port for external communication
#    depends_on:
#      - zookeeper
#
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#    ports:
#      - "9200:9200"
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.11.0
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.11.0
#    volumes:
#      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
#    ports:
#      - "5000:5000"
#    depends_on:
#      - kafka
#      - elasticsearch
volumes:
  mysql-data:
#  redis-data: